# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a200tffg1156-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Devel/projekty/TMS/lnls_out/tms_master/tms_master.cache/wt [current_project]
set_property parent.project_path D:/Devel/projekty/TMS/lnls_out/tms_master/tms_master.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet D:/Devel/projekty/TMS/lnls_out/tms_master/tms_master.runs/chipscope_ila_synth_1/chipscope_ila.dcp
set_property used_in_implementation false [get_files D:/Devel/projekty/TMS/lnls_out/tms_master/tms_master.runs/chipscope_ila_synth_1/chipscope_ila.dcp]
add_files -quiet D:/Devel/projekty/TMS/lnls_out/tms_master/tms_master.runs/vio_boot_synth_1/vio_boot.dcp
set_property used_in_implementation false [get_files D:/Devel/projekty/TMS/lnls_out/tms_master/tms_master.runs/vio_boot_synth_1/vio_boot.dcp]
read_vhdl -library xil_defaultlib {
  D:/Devel/projekty/TMS/lnls_out/import/genram_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wishbone_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/simple_uart_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_stream_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_slave_adapter.vhd
  D:/Devel/projekty/TMS/lnls_out/import/uart_baud_gen.vhd
  D:/Devel/projekty/TMS/lnls_out/import/uart_async_tx.vhd
  D:/Devel/projekty/TMS/lnls_out/import/uart_async_rx.vhd
  D:/Devel/projekty/TMS/lnls_out/import/simple_uart_wb.vhd
  D:/Devel/projekty/TMS/lnls_out/import/generic_sync_fifo.vhd
  D:/Devel/projekty/TMS/lnls_out/import/gencores_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/gc_sync_ffs.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_crossbar.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wr_fabric_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_tics.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_stream_generic_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_simple_uart.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_gpio_port.vhd
  D:/Devel/projekty/TMS/lnls_out/import/sdb_rom.vhd
  D:/Devel/projekty/TMS/lnls_out/import/memory_loader_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/fmc_adc_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/acq_core_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_tics.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_simple_uart.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_sdb_crossbar.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_gpio_port.vhd
  D:/Devel/projekty/TMS/lnls_out/import/spi2wbm_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/generic_dpram_sameclock.vhd
  D:/Devel/projekty/TMS/lnls_out/import/generic_dpram_dualclock.vhd
  D:/Devel/projekty/TMS/lnls_out/import/dbe_wishbone_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/wb_dbe_periph.vhd
  D:/Devel/projekty/TMS/lnls_out/import/spi2wbm_link.vhd
  D:/Devel/projekty/TMS/lnls_out/import/generic_dpram.vhd
  D:/Devel/projekty/TMS/lnls_out/import/fmc_general_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/bpm_pcie_a7_const_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_dpram.vhd
  D:/Devel/projekty/TMS/lnls_out/import/xwb_dbe_periph.vhd
  D:/Devel/projekty/TMS/lnls_out/import/sys_pll.vhd
  D:/Devel/projekty/TMS/lnls_out/import/spi_multiplexer.vhd
  D:/Devel/projekty/TMS/lnls_out/import/spi2wbm_link_top.vhd
  D:/Devel/projekty/TMS/lnls_out/import/project.vhd
  D:/Devel/projekty/TMS/lnls_out/import/position_calc_uvx_const_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/fmc_dio5chttl.vhd
  D:/Devel/projekty/TMS/lnls_out/import/dsp_cores_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/dbe_common_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/clk_gen.vhd
  D:/Devel/projekty/TMS/lnls_out/import/bpm_pcie_a7_pkg.vhd
  D:/Devel/projekty/TMS/lnls_out/import/dbe_bpm_dsp.vhd
}
read_xdc D:/Devel/projekty/TMS/lnls_out/import/dbe_bpm_dsp.xdc
set_property used_in_implementation false [get_files D:/Devel/projekty/TMS/lnls_out/import/dbe_bpm_dsp.xdc]

catch { write_hwdef -file dbe_bpm_dsp.hwdef }
synth_design -top dbe_bpm_dsp -part xc7a200tffg1156-1
write_checkpoint -noxdef dbe_bpm_dsp.dcp
catch { report_utilization -file dbe_bpm_dsp_utilization_synth.rpt -pb dbe_bpm_dsp_utilization_synth.pb }
